In [3]:
import numpy as np

## Exercise 1 : Array Creation And Manipulation


Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 2 : Type Conversion And Array Operations

Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])


In [5]:
np.array([3.14, 2.17, 0, 1, 2], dtype=int)

array([3, 2, 0, 1, 2])

## Exercise 3 : Working With Multi-Dimensional Arrays

Instructions Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr = np.arange(1, 10)
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [11]:
arr2 = np.random.rand(4, 5)
arr2

array([[0.05246252, 0.2978163 , 0.82608452, 0.30216441, 0.28085263],
       [0.43718881, 0.90877596, 0.85988525, 0.64974555, 0.23127507],
       [0.31406132, 0.65598829, 0.87076713, 0.74085367, 0.35301917],
       [0.50065819, 0.38711576, 0.47265959, 0.89955654, 0.76448601]])

## Exercise 5 : Indexing Arrays


Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array([20, 21, 22, 23, 24])

In [14]:
arr2[1]

array([0.43718881, 0.90877596, 0.85988525, 0.64974555, 0.23127507])

## Exercise 6 : Reversing Elements


Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])



In [15]:
arr3 = np.arange(10)
arr3[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Exercise 7 : Identity Matrix

Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Exercise 8 : Simple Aggregate Funcs

Instructions Find the sum and average of a given 1D array.

Expected Output:

Sum: 45, Average: 4.5

In [18]:
print(f'Sum: {arr3.sum()}, Average: {arr3.mean()}')

Sum: 45, Average: 4.5


## Exercise 9 : Create Array And Change Its Structure

Instructions Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:

array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

In [19]:
arr4 = np.arange(1, 21)
arr4.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Exercise 10 : Conditional Selection Of Values

Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])


In [21]:
arr3[arr3 % 2 == 1]

array([1, 3, 5, 7, 9])